server:
  port: 8081

spring:
  #配置rabbitMq 服务器
  rabbitmq:
    host: 123.57.76.15
    port: 5672
    username: admin
    password: admin
    virtual-host: /

#    123.57.76.15 root 111044czl..
#    http://123.57.76.15:15672/# rabbitMq服务器
