server:
  port: 8081

spring:
  #配置rabbitMq 服务器
  rabbitmq:
    host: 123.57.76.15
    port: 5672
    username: admin
    password: admin
    virtual-host: /

#    服务器 123.57.76.15 root 111044czl..
#    mysql  123.57.76.15:3306 root root
#    rabbitMq服务器 http://123.57.76.15:15672/#
