server:
  port: 8086

#服务名
spring:
  application:
    name: gateway

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   # 指定注册中心的地址
  instance:
    preferIpAddress: true

logging:
  level:
    com.czl.gateway: debug

