server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: 127.0.0.1         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false    #自身注册到Eureka Server上，默认为true
    fetchRegistry: false   #从其他Eureka Server获取注册信息，单节点设置为false，集群情况下可设置为true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #多个地址用逗号分割，单节点可不配置
  server:
    enable-self-preservation: false   #调试时关闭eureka注册中心的保护机制